version: "3.2"
services:
  keto-migrate:
    image: oryd/keto:v0.10.0-alpha.0
    links:
      - postgresd:postgresd
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://postgres:postgres@postgresd:5432/keto?sslmode=disable
    command: ["migrate", "up", "-y"]
    restart: on-failure
  keto:
    image: oryd/keto:v0.10.0-alpha.0
    links:
      - postgresd:postgresd
    volumes:
      - type: bind
        source: ./config/keto.yml
        target: /home/ory/keto.yml
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve -c /home/ory/keto.yml
    depends_on:
      - keto-migrate
    environment:
      - DSN=postgres://postgres:postgres@postgresd:5432/keto?sslmode=disable
    restart: on-failure
  postgresd:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keto
